<?php
/*
WARNING!!
This is a dynamically generated style sheet that is controlled by the Wordpress admin
"Theme Options" area. We suggest that you do not edit this file. If you would like to
use your own custom styles you can override the dynamic styling in the Wordpress admin
and use the standard style sheet provided with your theme located in your theme directory
called style.css.
*/

if (!defined('WP_ABSPATH')) define('WP_ABSPATH', dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/');
include_once(WP_ABSPATH.'wp-load.php');
include_once(WP_ABSPATH.'wp-includes/wp-db.php');
$fonts = Photocrati_Fonts::get_instance();

@header( 'Content-type: text/css' );

global $wpdb;

// Get styles from preset
$preset = Photocrati_Style_Manager::get_active_preset();
extract($preset->to_array());

$global = $wpdb->get_row("SELECT albuml_line_size FROM ".$wpdb->prefix."photocrati_gallery_settings WHERE id = 1", ARRAY_A);
foreach ($global as $key => $value) {
    $$key = $value;
}

$estyle = $wpdb->get_row("SELECT ecomm_back_color,ecomm_font_color,ecomm_line_color,ecomm_line_size,ecomm_but_color,ecomm_buttext_color,ecomm_butborder_color FROM ".$wpdb->prefix."photocrati_ecommerce_settings WHERE id = 1", ARRAY_A);
foreach ($estyle as $key => $value) {
    $$key = $value;
}

// adjust $one_column setting for legacy code that uses that setting value
$left_header = false;

if (strval($one_column) == 'left_header') {
	$left_header = true;
	$one_column = false;
}

// background images conversion
$image_setting_list = array('bg_image', 'header_bg_image', 'custom_logo_image');

foreach ($image_setting_list as $image_setting) {
	$$image_setting = Photocrati_Style_Manager::get_setting_image_url($image_setting);
}

// include specific skin
$style_dir = dirname(__FILE__) . DIRECTORY_SEPARATOR;
$style_file = null;

if (isset($style_skin) && $style_skin == 'modern') {
	$style_file = $style_dir . 'dynamic-style-modern.php';
}

if ($style_file == null || !file_exists($style_file)) {
	$style_file = $style_dir . 'dynamic-style-legacy.php';
}

if (file_exists($style_file)) {
	include($style_file);
}

