<?php
/*
WARNING!!
This is a dynamically generated style sheet that is controlled by the Wordpress admin
"Theme Options" area. We suggest that you do not edit this file. If you would like to
use your own custom styles you can override the dynamic styling in the Wordpress admin
and use the standard style sheet provided with your theme located in your theme directory
called style.css.
*/

if ($style_skin == 'modern') {
	$menu_skin = 'default';
}
else if ($style_skin == 'legacy') {
	$menu_skin = 'legacy';
}

$skin_path = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'menu' . DIRECTORY_SEPARATOR;
$skin_file = $skin_path . $menu_skin . '.css';
$skin_dyn = $menu_skin . '-dyn';
$skin_dyn_file = $skin_path . $skin_dyn . '.php';

if (!file_exists($skin_file)) {
	$menu_skin = 'base';
}

if (!file_exists($skin_dyn_file)) {
	$skin_dyn = null;
}

$extra_header_width = 0;
			
if ($left_header) {
	$header_position = 'fixed';
	$logo_menu_position = 'top-bottom'; /* hide in options */
	$menu_vertical_padding = 5; /* we use this for some padding in menu items, alternative is to have an extra check below and instead of $menu_vertical_padding use line-height of 2 */
		
	$extra_header_width = intval($header_width) + intval($header_margin_left) + intval($header_margin_right);

// when using left header and pixel based dimensions, ensure pixels represent the total layout dimension including the left header width
	$width_list = array('layout_width', 'layout_width_min', 'layout_width_max');

	foreach ($width_list as $width_name) {
		$unit_name = $width_name . '_unit';
		$unit = $$unit_name;
		
		if ($unit == 'px') {
			$width = $$width_name;
			
			$$width_name = $width - $extra_header_width;
		}
	}
}
else if (in_array($logo_menu_position, array('left-right', 'right-left'))) {
	$menu_vertical_padding = max(intval($menu_vertical_padding), 10);
}

if ($header_position == 'fixed' && $one_column) {
	$header_position = 'static';
}
?>

    /* Reset default browser styles */
    @import url('resets/reset.css');

    /* Rebuild default browser styles */
    @import url('resets/rebuild.css');

    /* Basic WordPress Styles */
    @import url('resets/wp.css');
    
    /* Basic Menu Styles */
    @import url('menu/<?php echo $menu_skin; ?>.css');
    
<?php 
	/* allow overriding of certain theme options-controlled dynamic properties */ 
	if ($skin_dyn != null): ?>
    /* Dynamic Menu Styles */
    @import url('menu/<?php echo $skin_dyn; ?>.php');
<?php endif ?>

    /* General Styles
    -------------------------------------------------------------- */

    /* The following section sets the basic body, H1-H5 and link styles */

    html {
    min-height		:	100%;
    }

    body {
    background		: <?php 
    if($bg_color <> 'transparent') {
    	if ($bg_opacity >= 100) {
  			echo '#' . $bg_color; 
    	}
    	else {
    		echo 'rgba(' . implode(',', Photocrati_Style_Manager::color_hex2rgb($bg_color)) . ',' . round($bg_opacity / 100, 2) . ')'; 
    	}
    }
    else { 
    	echo $bg_color; 
    }
    
    if($bg_image <> '') { ?> url(<?php echo $bg_image; ?>) <?php echo $bg_repeat . ' ' . $bg_attachment; } ?> 0 <?php echo $bg_top_offset; ?>px;
    <?php if ($bg_scale && $bg_scale != 'auto'): ?>
		-webkit-background-size: <?php echo $bg_scale; ?>;
		-moz-background-size: <?php echo $bg_scale; ?>;
		-o-background-size: <?php echo $bg_scale; ?>;
		background-size: <?php echo $bg_scale; ?>;
    <?php endif ?>
    padding-top 	: 	0;
    margin-top 		: 	0;
    min-height			:	100%;
    }
    
    pre {
    	max-width: 100%;
    	overflow: auto;
    }

    h1 { /* The H1 tag is used for page titles, and post titles on blog page. */
    font-size 		: 	<?php echo $h1_size; ?>px;
    font-family		:	<?php echo $fonts->get_css_value($h1_font_style)?>;
    color			: 	#<?php echo $h1_color; ?>;
    text-decoration :   <?php echo $h1_font_decoration ?>;
    clear			:	none;
<?php if($h1_font_case != 'none') { ?>
    text-transform	:	<?php echo $h1_font_case ?>;
<?php } ?>
<?php if($h1_font_weight) { ?>
    font-weight		:	<?php echo $h1_font_weight?>;
<?php } ?>
<?php if ($h1_font_italic): ?>
    font-style      :   <?php echo $h1_font_italic ?>;
<?php endif ?>
<?php if($h1_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    }

    h1 a:link, .h1 a:active, .h1 a:visited {
    color			: 	#<?php echo $h1_color; ?>;
    }

    div.post h1.entry-title {
    line-height: 1.20em;
    }
    
    div.post h1.entry-title a {
    color: #<?php echo $h1_color; ?>;
    }

    h2 { /* The H2 tag is used for post titles */
    font-size 		: 	<?php echo $h2_size; ?>px;
    font-family		:	<?php echo $fonts->get_css_value($h2_font_style)?>;
    color			: 	#<?php echo $h2_color; ?>;
    text-decoration :   <?php echo $h2_font_decoration ?>;
    clear			:	none;
<?php if ($h2_font_case != 'none'): ?>
    text-transform  :   <?php echo $h2_font_case ?>;
<?php endif ?>
<?php if($h2_font_weight): ?>
    font-weight		:	<?php echo $h2_font_weight ?>;
<?php endif ?>
<?php if ($h2_font_italic): ?>
    font-style      :   <?php echo $h2_font_italic ?>;
<?php endif ?>
<?php if($h2_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top      :	20px;
    margin-bottom   :   15px;
    }

    h2 a:link, .h2 a:active, .h2 a:visited {
    color			: 	#<?php echo $h2_color; ?>;
    }

    div.post h2.entry-title {
    line-height: 1.20em;
    }

    div.post h2.entry-title a {
    color: 	#<?php echo $h2_color; ?>;
    }

    h3 {
    font-size 		: 	<?php echo $h3_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($h3_font_style) ?>;
    color			: 	#<?php echo $h3_color; ?>;
    text-decoration :   <?php echo $h3_font_decoration ?>;
    clear			:	none;
<?php if ($h3_font_case != 'none'): ?>
    text-transform  :   <?php echo $h3_font_case ?>;
<?php endif ?>
<?php if ($h3_font_weight): ?>
    font-weight     :   <?php echo $h3_font_weight ?>;
<?php endif ?>
<?php if ($h3_font_italic): ?>
    font-style      :   <?php echo $h3_font_italic ?>;
<?php endif ?>
<?php if($h3_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top		:	20px;
    margin-bottom	:	15px;
    }

    h3 a:link, .h1 a:visited {
    color			: 	#<?php echo $h3_color; ?>;
    }

    h4 {
    font-size 		: 	<?php echo $h4_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($h4_font_style) ?>;
    color			: 	#<?php echo $h4_color; ?>;
    text-decoration :   <?php echo $h4_font_decoration ?>;
    clear			:	none;
<?php if ($h4_font_case != 'none'): ?>
    text-transform  :   <?php echo $h4_font_case ?>;
<?php endif ?>
<?php if ($h4_font_weight): ?>
    font-weight		:	<?php echo $h4_font_weight ?>;
<?php endif ?>
<?php if ($h4_font_italic): ?>
    font-style      :   <?php echo $h4_font_italic ?>;
<?php endif ?>
<?php if($h4_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top		:	20px;
    margin-bottom	:	15px;
    }

    h4 a:link, .h4 a:visited {
    color			: 	#<?php echo $h4_color; ?>;
    }

    h5 {
    font-size 		: 	<?php echo $h5_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($h5_font_style) ?>;
    text-decoration :   <?php echo $h5_font_decoration ?>;
    color			: 	#<?php echo $h5_color; ?>;
    clear			:	none;
<?php if ($h5_font_case != 'none'): ?>
    text-transform  :   <?php echo $h5_font_case ?>;
<?php endif ?>
<?php if($h5_font_weight) { ?>
    font-weight		:	<?php echo $h5_font_weight ?>;
<?php } ?>
<?php if ($h5_font_italic): ?>
    font-style      :   <?php echo $h5_font_italic ?>;
<?php endif ?>
<?php if($h5_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top		:	20px;
    margin-bottom	:	15px;
    }

    h5 a:link, .h5 a:visited {
    color			: 	#<?php echo $h5_color; ?>;
    }

    a:link,a:visited { /* This styles the majority of the on page links. The sidebar links can be styled seperately */
    color 			: 	#<?php echo $link_color; ?>;
    text-decoration : 	none;
    }

    a:hover,a:active {
    color 			: 	#<?php echo $link_hover_color; ?>;
    text-decoration : 	<?php echo $link_hover_style; ?>;
    }

    .clear {
    width			:	100%;
    clear			:	both;
    height			:	1px;
    }


    /* General Page Styles
    -------------------------------------------------------------- */

    #main_container {
    min-height:	100%;
    z-index:	-1;
<?php if($one_column): ?>
<?php echo Photocrati_Style_Manager::build_width_property_set($layout_width, $layout_width_unit, $layout_width_min, $layout_width_min_unit, $layout_width_max, $layout_width_max_unit); ?>
<?php if (!$left_header && $layout_spacing > 0): ?>
    margin			:	<?php echo intval($layout_spacing); ?>px auto;
<?php else: ?>
    margin			:	0 auto;
<?php endif ?>
    background		:	<?php 
	  if($one_column_color <> 'transparent') {
	  	if ($one_column_opacity >= 100) {
	  		echo '#' . $one_column_color; 
	  	} 
	  	else {
	  		echo 'rgba(' . implode(',', Photocrati_Style_Manager::color_hex2rgb($one_column_color)) . ',' . round($one_column_opacity / 100, 2) . ')'; } 
	  } 
	  else { 
	  	echo $one_column_color; 
	  } 
	  ?>;
<?php endif ?>
<?php if($container_drop_shadow_size > 0): ?>
		-moz-box-shadow: 0px 0px <?php echo $container_drop_shadow_size; ?>px rgb(0, 0, 0);
		-webkit-box-shadow: 0px 0px <?php echo $container_drop_shadow_size; ?>px rgb(0, 0, 0);
		box-shadow: 0px 0px <?php echo $container_drop_shadow_size; ?>px rgb(0, 0, 0);
<?php endif ?>
    }
    #main_container:before,
		#main_container:after {
			content: " ";
			display: table;
		}
		#main_container:after {
			clear: both;
		}

    #wrapper { /* This sets the width of the entire site */
    position: relative;
<?php if($one_column): ?>
		width: auto;
    margin: 0 15px;
<?php else: ?>
<?php if($left_header): ?>
    margin-left: <?php echo ((int)$header_width) + intval($header_margin_left) + intval($header_margin_right); ?>px;
<?php else: ?>
    margin: 0 auto;
<?php endif ?>
<?php endif ?>
    overflow		:	visible;
    }
		#wrapper:before,
		#wrapper:after {
			content: " ";
			display: table;
		}
		#wrapper:after {
			clear: both;
		}    
    
    #main {
    position 		: 	relative;
<?php if($one_column): ?>
		width: auto;
<?php else: ?>
<?php echo Photocrati_Style_Manager::build_width_property_set($layout_width, $layout_width_unit, $layout_width_min, $layout_width_min_unit, $layout_width_max, $layout_width_max_unit); ?>
<?php endif ?>
<?php if($left_header && $layout_alignment == 'left'): ?>
    margin: 0;
<?php else: ?>
    margin: 0 auto;
<?php endif ?>
<?php if (!$left_header): ?>
<?php if ($header_position == 'fixed'): ?>
    margin-top: <?php echo ((int)$header_height) + 10; ?>px;
<?php endif ?>
    margin-bottom: 15px;
<?php endif ?>
	  background		: <?php 
	  if($container_color <> 'transparent') {
	  	if ($container_opacity >= 100) {
	  		echo '#' . $container_color; 
	  	} 
	  	else {
	  		echo 'rgba(' . implode(',', Photocrati_Style_Manager::color_hex2rgb($container_color)) . ',' . round($container_opacity / 100, 2) . ')'; } 
	  } 
	  else { 
	  	echo $container_color; 
	  } 
	  ?>;
    border			:	<?php echo $container_border; ?>px solid #<?php echo $container_border_color; ?>;
    }
		#main:before,
		#main:after {
			content: " ";
			display: table;
		}
		#main:after {
			clear: both;
		}    

    #container { /* This sets the width of the main content area */
    margin			: 	<?php echo $container_padding; ?>px;
    }

    /* Menu Styles
    -------------------------------------------------------------- */

    #menu_wrapper { /* This is the main menu container */
<?php if($logo_menu_position == 'left-right') { ?>
    width 			: 	64%;
    <?php if($one_column_logo) { ?>
        margin			: 	<?php echo $one_column_margin; ?>px 0;
    <?php } else { ?>
        margin			: 	<?php echo min($header_height, intval(round(($header_height - ($menu_font_size + ($menu_vertical_padding * 2))) / 2))); ?>px 0;
    <?php } ?>
    float: 	right;
    text-align 		: 	right;
<?php } else if($logo_menu_position == 'right-left') { ?>
    width 			: 	64%;
    <?php if($one_column_logo) { ?>
        margin			: 	<?php echo $one_column_margin; ?>px 0;
    <?php } else { ?>
        margin			: 	<?php echo min($header_height, intval(round(($header_height - ($menu_font_size + ($menu_vertical_padding * 2))) / 2))); ?>px 0;
    <?php } ?>
    float 			: 	left;
    text-align 		: 	left;
<?php } else if($logo_menu_position == 'bottom-top') { ?>
    clear			:	both;
    width 			: 	auto;
    margin			: 	0 0 0.55em 0;
    text-align 		: 	center;
<?php } else if($logo_menu_position == 'top-bottom') { ?>
    width 			: 	auto;
    margin			: 	0.55em 0 0 0;
    clear			:	both;
    text-align 		: 	center;
<?php } ?>
    overflow 		: 	visible;
<?php if($logo_menu_position == 'right-left') { ?>
    z-index			:	4;
<?php } else { ?>
    z-index			:	4;
<?php } ?>
    background		:	<?php 
	  if($menu_container_color <> 'transparent') {
	  	if ($menu_container_opacity >= 100) {
	  		echo '#' . $menu_container_color; 
	  	} 
	  	else {
	  		echo 'rgba(' . implode(',', Photocrati_Style_Manager::color_hex2rgb($menu_container_color)) . ',' . round($menu_container_opacity / 100, 2) . ')'; } 
	  } 
	  else { 
	  	echo $menu_container_color; 
	  } 
	  ?>;
    }

    #menu_wrapper .photocrati-menu {
    	margin: 0 3px; /* this seems required for some rounding errors in FF which make a scrollbar appear otherwise */
    }
    
		.photocrati-menu > ul > li > a {
			padding-top: <?php echo intval($menu_vertical_padding); ?>px;
			padding-bottom: <?php echo intval($menu_vertical_padding); ?>px;
		}
    
<?php if ($left_header): ?>
<?php if ($menu_skin != 'legacy'): ?>
    /* adjustments for side header, menu needs to change... maybe place this under the -dynamic.php menu skin? */
  #menu_wrapper {
<?php if ($menu_alignment != 'default'): ?>
		text-align: <?php echo $menu_alignment; ?>;
<?php endif ?>
  }
  
  #menu_wrapper .photocrati-menu {
  	margin: 0;
  }
	.photocrati-menu > ul > li {
		display: block;
	}
	.photocrati-menu .menu-item-has-children ul {
		left: 100%;
		top: 0;
		z-index: 10000;
	}
	.photocrati-menu .menu-item-has-children:last-child ul {
		left: 100%;
		top: 0;
	}
	.photocrati-menu .menu-item-has-children:last-child .menu-item-has-children ul {
		left: 100%;
		top: 0;
	}
<?php endif ?>
<?php endif ?>

<?php
 /* These definitions apply specific theme options to the menus */ 
?>

    .photocrati-menu a {
    font-size: <?php echo $menu_font_size; ?>px;
<?php if($menu_font_case == '' || $menu_font_case == 'uppercase'): ?>
    text-transform:	uppercase;
<?php endif ?>
    }
    
    .photocrati-menu a:link, .photocrati-menu a:visited {
    color: 	#<?php echo $menu_font_color; ?>;
    font-family: <?php echo $fonts->get_css_value($menu_font_style) ?>;
<?php if ($menu_font_weight): ?>
    font-weight: <?php echo $menu_font_weight ?>;
<?php endif ?>
<?php if ($menu_font_italic): ?>
    font-style: <?php echo $menu_font_italic ?>;
<?php endif ?>
    text-decoration: <?php echo $menu_font_decoration ?>;
    background: <?php if($menu_style <> 'transparent') { echo Photocrati_Style_Manager::build_background_color_property($menu_color, $menu_color_opacity); } else { echo $menu_style; } ?>;
    }
    
    .photocrati-menu a:link .photocrati-menu-expander, 
    .photocrati-menu a:visited .photocrati-menu-expander {
    border-color: 	#<?php echo $menu_font_color; ?>;
    }
    
    .photocrati-menu a:hover,.photocrati-menu a:active,
    .photocrati-menu .current_page_item a:link,
    .photocrati-menu .current_page_item a:visited  {
    color: #<?php echo $menu_font_hover_color; ?>;
    background: <?php if($menu_style <> 'transparent') { echo Photocrati_Style_Manager::build_background_color_property($menu_hover_color, $menu_hover_color_opacity); } else { echo $menu_style; } ?>;
    }
    
    .photocrati-menu a:hover .photocrati-menu-expander,
    .photocrati-menu a:active .photocrati-menu-expander,
    .photocrati-menu .current_page_item a:link .photocrati-menu-expander,
    .photocrati-menu .current_page_item a:visited .photocrati-menu-expander  {
    border-color: #<?php echo $menu_font_hover_color; ?>;
    }

    .photocrati-menu .current_page_item ul a:link,
    .photocrati-menu .current_page_item ul a:visited {
    color: #<?php echo $menu_font_hover_color; ?>;
    background: <?php if($menu_style <> 'transparent') { echo Photocrati_Style_Manager::build_background_color_property($menu_hover_color, $menu_hover_color_opacity); } else { echo $menu_style; } ?>;
    }

    .photocrati-menu .current_page_item ul a:link .photocrati-menu-expander,
    .photocrati-menu .current_page_item ul a:visited .photocrati-menu-expander {
    border-color: #<?php echo $menu_font_hover_color; ?>;
    }

    .photocrati-menu .current_page_item ul li a:hover,
    .photocrati-menu .current_page_item ul li a:active {
    color: #<?php echo $menu_font_hover_color; ?>;
    background: <?php if($menu_style <> 'transparent') { echo Photocrati_Style_Manager::build_background_color_property($menu_hover_color, $menu_hover_color_opacity); } else { echo $menu_style; } ?>;
    }

    .photocrati-menu .current_page_item ul li a:hover .photocrati-menu-expander,
    .photocrati-menu .current_page_item ul li a:active .photocrati-menu-expander {
    border-color: #<?php echo $menu_font_hover_color; ?>;
    }

    .photocrati-menu ul li ul li a:link,
    .photocrati-menu ul li ul li a:visited,
    .photocrati-menu ul li.current_page_item ul li a:link,
    .photocrati-menu ul li.current_page_item ul li a:visited {
    color: #<?php echo $submenu_font_color; ?>;
    background:	<?php echo Photocrati_Style_Manager::build_background_color_property($submenu_color, $submenu_color_opacity); ?>;
    font-size: <?php echo $submenu_font_size; ?>px;
    font-family: <?php echo $fonts->get_css_value($submenu_font_style) ?>;
<?php if ($submenu_font_case == '') $submenu_font_case = 'uppercase'; ?>
    text-transform: <?php echo $submenu_font_case ?>;
    text-decoration: <?php echo $submenu_font_decoration ?>;
<?php if ($submenu_font_weight): ?>
    font-weight: <?php echo $submenu_font_weight ?>;
<?php endif ?>
<?php if ($submenu_font_italic): ?>
    font-style: <?php echo $submenu_font_italic ?>;
<?php endif ?>
    }

    .photocrati-menu ul li ul li a:link .photocrati-menu-expander,
    .photocrati-menu ul li ul li a:visited .photocrati-menu-expander,
    .photocrati-menu ul li.current_page_item ul li a:link .photocrati-menu-expander,
    .photocrati-menu ul li.current_page_item ul li a:visited .photocrati-menu-expander {
    border-color: #<?php echo $submenu_font_color; ?>;
    }

    .photocrati-menu ul li ul li a:hover,
    .photocrati-menu ul li ul li a:active,
    .photocrati-menu ul li.current_page_item ul li a:hover,
    .photocrati-menu ul li.current_page_item ul li a:active,
    .photocrati-menu ul li ul li.current_page_item a:link,
    .photocrati-menu ul li ul li.current_page_item a:visited {
    color: #<?php echo $submenu_font_hover_color; ?>;
    background:	<?php echo Photocrati_Style_Manager::build_background_color_property($submenu_hover_color, $submenu_hover_color_opacity); ?>;
    }

    .photocrati-menu ul li ul li a:hover .photocrati-menu-expander,
    .photocrati-menu ul li ul li a:active .photocrati-menu-expander,
    .photocrati-menu ul li.current_page_item ul li a:hover .photocrati-menu-expander,
    .photocrati-menu ul li.current_page_item ul li a:active .photocrati-menu-expander,
    .photocrati-menu ul li ul li.current_page_item a:link .photocrati-menu-expander,
    .photocrati-menu ul li ul li.current_page_item a:visited .photocrati-menu-expander {
    border-color: #<?php echo $submenu_font_hover_color; ?>;
    }

    .footer_menu { /* This sets the z-index of the footer menu */
    z-index			:	2;
    }

    .footer_menu ul, .footer_menu ul * { /* This sets the width of the footer menu */
    overflow 		: 	visible;
    z-index			:	2;
    list-style		: 	none;
    margin			:	0 auto;
    padding			:	0;
    }

    .footer_menu ul li { /* This sets the position of the footer menu items */
    position		:	relative;
    display			: 	inline;
    margin			:	0 7px 0 7px;
    font-weight		:	bold;
    text-transform	: 	uppercase;
    font-size		: 	14px;
    }


    /* Header Styles
    -------------------------------------------------------------- */

    #header { /* This sets the color of the header */
    background		:	<?php 
    if($header_bg_color <> 'transparent') {
    	if ($header_opacity >= 100) {
    		echo '#' . $header_bg_color;
    	}
    	else {
    		echo 'rgba(' . implode(',', Photocrati_Style_Manager::color_hex2rgb($header_bg_color)) . ',' . round($header_opacity / 100, 2) . ')'; 
    	}
    } 
    else {
    	echo $header_bg_color; 
    } 
    if($header_bg_image <> '') { ?> url(<?php echo $header_bg_image; ?>) bottom <?php echo $header_bg_repeat; ?><?php } ?>;
<?php if ($left_header): ?>
    height: 100%;
    width: <?php echo intval($header_width); ?>px;
    position : <?php echo $header_position; ?>;
    left: <?php echo intval($header_margin_left); ?>px;
    /*top: <?php echo intval($header_margin_top); ?>px;*/
<?php if ($header_position == 'fixed'): ?>
    z-index: 2;
<?php endif ?>
<?php else: ?>
    width: auto;
    min-height:	<?php echo $header_height; ?>px;
    position : <?php echo $header_position; ?>;
<?php if ($header_position == 'fixed'): ?>
    z-index: 2;
    width: 100%;
<?php endif ?>
    margin-bottom	:	10px;
<?php endif ?>
<?php if($header_drop_shadow_size > 0): ?>
		-moz-box-shadow: 0px <?php echo intval(($header_drop_shadow_size) / 2); ?>px <?php echo $header_drop_shadow_size; ?>px rgb(0, 0, 0);
		-webkit-box-shadow: 0px <?php echo intval(($header_drop_shadow_size) / 2); ?>px <?php echo $header_drop_shadow_size; ?>px rgb(0, 0, 0);
		box-shadow: 0px <?php echo intval(($header_drop_shadow_size) / 2); ?>px <?php echo $header_drop_shadow_size; ?>px rgb(0, 0, 0);
<?php endif ?>
    }

    #masthead { /* This sets total width and position of the header */
<?php if($one_column || $left_header || in_array($logo_menu_position, array('bottom-top', 'top-bottom'))): ?>
		width: auto;
<?php else: ?>
    width: <?php echo Photocrati_Style_Manager::build_width_property($layout_width, $layout_width_unit); ?>;
    min-width: <?php echo Photocrati_Style_Manager::build_width_property($layout_width_min, $layout_width_min_unit); ?>;
    max-width: <?php echo Photocrati_Style_Manager::build_width_property($layout_width_max, $layout_width_max_unit, 'none'); ?>;
<?php endif ?>
    margin: 0 auto;
    position: relative;
    }
    
		#masthead:before,
		#masthead:after {
			content: " ";
			display: table;
		}
		#masthead:after {
			clear: both;
		}

    #branding { /* This sets the size and position of the logo area on the header */
    display			:	block;
<?php if($logo_menu_position == 'left-right') { ?>
    float 			: left;
    position		:	relative;
    margin			:	<?php /* Note: we remove 25 here because legacy was using position absolute which means the margin had to include the menu height */ echo max(0, intval($header_logo_margin_above)); ?>px 0 <?php echo $header_logo_margin_below; ?>px 0;
    <?php if($one_column_logo) { ?>
        width: auto;
    <?php } else { ?>
        width: 35%; /* was 400px */
    <?php } ?>
    z-index			:	3;
<?php } else if($logo_menu_position == 'right-left') { ?>
    float 			: 	right;
    text-align		:	right;
    position		:	relative;
    margin			:	<?php /* Note: we remove 25 here because legacy was using position absolute which means the margin had to include the menu height */ echo max(0, intval($header_logo_margin_above)); ?>px 0 <?php echo $header_logo_margin_below; ?>px 0;
    <?php if($one_column_logo) { ?>
        width 			: 	35%;
    <?php } else { ?>
        width 			: 	35%;
    <?php } ?>
    z-index			:	3;
<?php } else if($logo_menu_position == 'bottom-top') { ?>
    width 			: 	100%;
    text-align 		: 	center;
    margin			:	<?php /* Note: we remove 60 here because legacy was using position absolute which means the margin had to include the menu height */ echo max(0, intval($header_logo_margin_above) - 60); ?>px 0 <?php echo $header_logo_margin_below; ?>px 0;
    <?php if($one_column_logo) { ?>
        position		:	relative;
    <?php } ?>
<?php } else if($logo_menu_position == 'top-bottom') { ?>
    width 			: 	100%;
    text-align 		: 	center;
    margin			:	<?php /* Note: we remove 10 here because legacy was using position absolute which means the margin had to include the menu height */ echo max(0, intval($header_logo_margin_above) - 10); ?>px 0 <?php echo $header_logo_margin_below; ?>px 0;
    <?php if($one_column_logo) { ?>
        position		:	relative;
    <?php } ?>
<?php } ?>
    }
    
    #branding #blog-title {
<?php if($logo_menu_position == 'left-right'): ?>
<?php if($one_column): ?>
    margin-left: 15px;
<?php elseif(!$left_header): ?>
    margin-left: <?php echo $header_logo_margin_side; ?>px;
<?php endif ?>
<?php elseif($logo_menu_position == 'right-left'): ?>
<?php if($one_column): ?>
    margin-right: 15px;
<?php elseif(!$left_header): ?>
    margin-right: <?php echo $header_logo_margin_side; ?>px;
<?php endif ?>
<?php endif ?>
		word-wrap: break-word;
    }

    #branding a { /* This sets the color and style of the wordpress title */
    display: block;
    text-decoration: none;
    }
    
    #branding img {
    	max-width: 100%;
<?php if ($header_position == 'fixed' && false /* disabled for now */): ?>
    	max-height: <?php echo ((int)$header_height) - (((int)$header_logo_margin_above) + ((int)$header_logo_margin_below)); ?>px;
<?php endif ?>
    	width: auto;
    	height: auto;
    }

    #branding h1 { /* This sets the color of the wordpress title */
    font-size		:	<?php echo $title_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($title_style) ?>;
    color			: 	#<?php echo $title_color; ?>;
    line-height		:	<?php echo $title_size + 2; ?>px;
    border			:	0;
    margin-top		:	15px;
    margin-bottom	:	5px;
    padding			:	0;
<?php if($logo_menu_position == 'left-right') { ?>
    text-align		:	left;
<?php } else if($logo_menu_position == 'right-left') { ?>
    text-align		:	right;
<?php } else { ?>
    text-align		:	center;
<?php } ?>
<?php if($title_font_case == 'uppercase') { ?>
    text-transform	:	uppercase;
<?php } else { ?>
    text-transform	:	none;
<?php } ?>
<?php if($title_font_weight) { ?>
    font-weight		:	<?php echo $title_font_weight ?>;
<?php } ?>
<?php if ($title_italic): ?>
	font-style      :   italic;
<?php endif ?>
    }

    #branding .description { /* This sets the font size and color for the description line if you are using the Wordpress title and description */
    font-size		:	<?php echo $description_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($description_style) ?>;
    color			: 	#<?php echo $description_color; ?>;
<?php if ($description_font_style == 'uppercase'): ?>
    text-transform  :   uppercase;
<?php endif ?>
    text-decoration :   <?php echo $description_font_decoration ?>;
<?php if ($description_font_weight): ?>
    font-weight     :   <?php echo $description_font_weight ?>;
<?php endif ?>
<?php if ($description_font_italic): ?>
    font-style      :   <?php echo $description_font_italic ?>;
<?php endif ?>
/*
<?php if($logo_menu_position == 'left-right') { ?>
    margin-left		:	3px;
<?php } ?>
<?php if($logo_menu_position == 'right-left') { ?>
    margin-right	:	5px;
<?php } ?>
*/
    }

    /* Content Styles
    -------------------------------------------------------------- */

    #content { /* This sets the width of the page content area  */
    position		:	relative;
    margin			: 	0;
    width			:	100%;
    z-index			:	1;
    }

    #content-sm { /* This sets the width of the blog content area  */
<?php if ($preset->is_sidebar_enabled()): ?>
    width			:	<?php echo (int)$content_width - 5; ?>%;
	<?php if ($sidebar_alignment == 'right'): ?>
    float			:	left;
	<?php elseif ($sidebar_alignment == 'left'): ?>
    float			:	right;
	<?php endif ?>
<?php else: ?>
    width			:	<?php echo (int)$content_width; ?>%;
    float			:	left;
<?php endif ?>
    }

    #content, #content-sm { /* This sets the font size and style on the blog and pages  */
    color 			: 	#<?php echo $font_color; ?>;
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    text-decoration :   <?php echo $font_decoration ?>;
<?php if ($font_weight): ?>
    font-weight     :   <?php echo $font_weight ?>;
<?php endif ?>
<?php if ($font_italic): ?>
    font-style      :   <?php echo $font_italic ?>;
<?php endif ?>
<?php if ($font_case != 'none'): ?>
    text-transform  :   <?php echo $font_case ?>;
<?php endif ?>
    }

    #content p, #content-sm p { /* This sets the paragraph spacing and line height  */
    line-height		: 	<?php echo $p_line; ?>px;
    margin-bottom	: 	<?php echo $p_space; ?>px;
    }

    p {
    margin-bottom	:	0.5em;
    }

    .post { /* This sets a small margin at the bottom of posts  */
    margin			: 	0 0 3em 0;
    }

    #nav-above { /* This hides the navigation above blog posts*/
    display			:	none;
    }

    #nav-above, #nav-below { /* Styles post navigation that appears above and below blog posts. */
    font-family			: 	'Open Sans', sans-serif;
    }

    .entry-content, .entry-summary { /* This sets a small margin at the top of the post content to make space between the title/meta area  */
    margin			: 	1.5em 0 0 0;
    }

    blockquote { /* This styles blockquotes in blog posts  */
    border-left		:	2px solid #E1E1E1;
    margin-left		:	25px;
    padding-left	:	15px;
    }


    /* Post Styles
    -------------------------------------------------------------- */

    .navigation { /* This sets a small margin below the post navigation on a single post */
    margin			: 	0 0 1.5em 0;
    overflow		: 	auto;
    }
    
    .size-full,
    .entry-content img,
    .entry-summary img { /* This sets a border around images with captions in posts */
    max-width: 100% !important;
    height: auto;
    }
    .entry-content .wp-caption,
    .entry-summary .wp-caption {
    max-width: 100% !important;
    }

    .entry-meta,
    .entry-utility { /* This sets the font size and style on post meta. This is the date, post by and comment links below the post title. */
    color 			: 	#<?php echo $font_color; ?>;
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    font-style 		: 	normal;
    text-transform	:	uppercase;
    font-size		: 	10px;
    clear 			: 	both;
    }

    .entry-meta {
<?php if ($blog_meta_pre_alignment != 'default'): ?>
		text-align: <?php echo $blog_meta_pre_alignment; ?>;
<?php endif ?>
    /* padding-left	: 	4px; not sure why this was here */
    }

    div.entry-date, .month, .day, .year { /* This aligns the post date on one line rather than stacked on top of each other. */
    display			: 	inline;
    }

    .entry-utility { /* This styles the blog post footer meta. */
    border-top		: 	1px solid #999;
<?php if ($blog_meta_post_alignment != 'default'): ?>
		text-align: <?php echo $blog_meta_post_alignment; ?>;
<?php endif ?>
    }


    /* Post Comment Styles
    -------------------------------------------------------------- */

    .comments ol { /* This removes the numbers from the comment list */
    list-style		:	none;
    margin-top		:	10px;
    }

    .comments li { /* This clears each comment block to a new line and adds a margin */
    width			:	100%;
    clear			:	both;
    min-height		:	100px;
    }

    .comments ul.children { /* This clears each comment block to a new line and adds a margin */
    list-style		:	none;
    margin-top		:	30px;
    }

    .comments .comment-wrapper { /* This sets the style for the comment wrapper */
    display			:	block;
    }

    p#comment-notes {
    font-size		: 	13px;
    }

    div.comment-meta a.commentauthor:link, a.commentauthor:visited { /* This styles the comment author name text. */
    color			: 	#3e3e3e;
    margin-bottom: 3px;
    }

    .comments .comment-author { /* This sets the style for the comment author icon */
    float			:	left;
    width			:	13%;
    margin-right	:	4%;
    }

    .comment-author img { /* This sets the size of comment avatars */
    width			: 	65px;
    height			: 	65px;
    }

    .comments .content-wrapper { /* This sets the style for the comment meta and content */
    float			:	left;
    width			:	83%;
    }

    .comments .comment-content { /* This sets a small margin between the meta and comment content */
    margin-top		:	0px;
    margin-bottom	: 	40px;
    }

    .comment-content { /* This styles the bottom of the comment text. */
    border-bottom	: 	1px solid #e1e1e1;
    }

    div.comment-meta { /* This is the comment author, date and permalink styles. */
    line-height		: 	1;
    padding-bottom	: 	3px;
    }

    div.comment-meta a.commentauthor:link, a.commentauthor:visited { /* This styles the comment author name. */
    font-size		: 	18px;
    font-weight		: 	bold;
    display			: 	block;
    }

    div.comment-meta .commentdate { /* This styles the comment date. */
    font-size		: 	14px;
    color			: 	#999;
    }

    div.comment-meta .commentpermalink { /* This styles the comment permalink. */
    font-size		: 	12px;
    }

    .comment-meta, .comment-reply-link { /* This styles the comment meta and reply link */
    font-family		: 	'Open Sans', sans-serif;
    }

    .comment-reply-link { /* This styles the comment reply link. */
    float			: 	right;
    margin-top		: 	-20px;
    font-weight		: 	bold;
    font-size		: 	14px;
    }

    div#cancel-comment-reply, span.loggedin, span.logout { /* This styles the 'cancel comment reply' link, logged in and logged out link. */
    font-size		: 	13px;
    }

    div#respond { /* This styles the comment reply form. */
    padding-bottom	: 	40px;
    }

    #respond h3 { /* This styles the comment reply h3 title. */
    margin-bottom	: 	-5px;
    }

    span.unapproved {
    font-style 		: 	italic;
    }

    #comments #respond input#author, #respond input#email, #respond input#url { /* This styles the comment form. */
    background		: 	#fdfdfd;
    color			: 	#a1a1a1;
    height			: 	24px;
    border			: 	2px solid #ccc;
    }
    
    #comments div#form-section-comment .form-textarea {
    	margin-right: 4px;
    	overflow: visible;
    }

    #comments div#form-section-comment textarea { /* This styles the comment form. */
    width			: 	100%;
    background		: 	#fdfdfd;
    color			: 	#252525;
    font-size		: 	14px;
    border			: 	2px solid #ccc;
    }

    #comments input#submit {
    background  :  #3e3e3e;
    border   :  0px;
    border-radius :  5px;
    padding   :  10px 20px;
    margin-top  :  15px;
    color   :  #fff;
    font-family  :  Open Sans, 'arial black', sans-serif;
    font-size  :  13px;
    font-weight  :  bold;
    }

    #comments input#submit:hover {
    background			: 	#<?php echo $link_color; ?>;
    cursor				:	pointer;
    }

    img.wp-smiley{  /* This sets no border around smileys */
    border			:	none;
    }


    /* Sidebar Styles
    -------------------------------------------------------------- */

    #sidebar { /* This sets the size of the sidebar as well as the font size and style */
    <?php if ($sidebar_alignment == 'right') {
    	echo "    " . 'float: right;' . "\n";
    }
    else {
    	echo "    " . 'float: left;' . "\n";
    }
    ?>
    width			: 	<?php echo $sidebar_width; ?>%;
    padding-top		: 	13px;
    background		:	<?php 
    if($sidebar_bg_color <> 'transparent') {
    	if ($sidebar_opacity >= 100) {
  			echo '#' . $sidebar_bg_color; 
    	}
    	else {
    		echo 'rgba(' . implode(',', Photocrati_Style_Manager::color_hex2rgb($sidebar_bg_color)) . ',' . round($sidebar_opacity / 100, 2) . ')'; 
    	}
    } 
    else { 
    	echo $sidebar_bg_color; 
    }
    ?>;
    <?php
    ?> 
    text-align		:	center;
    color			:	#<?php echo $sidebar_font_color; ?>;
    font-size		:	<?php echo $sidebar_font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($sidebar_font_style) ?>;
    text-decoration :   <?php echo $sidebar_font_decoration ?>;
<?php if ($sidebar_font_weight): ?>
    font-weight     :   <?php echo $sidebar_font_weight ?>;
<?php endif ?>
<?php if ($sidebar_font_italic): ?>
    font-style      :   <?php echo $sidebar_font_italic ?>;
<?php endif ?>
<?php if ($sidebar_font_case != 'none'): ?>
    text-transform  :   <?php echo $sidebar_font_case ?>;
<?php endif ?>
    }

    #sidebar a { /* This sets the color of the sidebar links */
    color			:	#<?php echo $sidebar_link_color; ?>;
    }

    #sidebar a:hover,
    #sidebar a:active { /* This sets the color and style of the hover and active states of the sidebar links */
    color			:	#<?php echo $sidebar_link_hover_color; ?>;
    text-decoration	:	<?php echo $sidebar_link_hover_style; ?>;
    }

    #sidebar .social-media { /* This sets the padding of the social media icons in the sidebar */
    text-align		:	left;
    padding			:	10px 10px 5px 10px;
    }

    #sidebar .social-media img { /* This sets a small margin to the right of each of the social media icons */
    border			:	0;
    margin-right	:	5px;
    }

    #primary, #primary_custom { /* This sets the position and width of the widget area */
    float   :  right;
    overflow  :  hidden;
    width    :  100%;
    padding-left : 0%;
    text-align  : left;
    }

    #sidebar #primary { /* ensures there is some padding between the border of the sidebar and it's content */
        width: 92%;
        margin: 0px auto;
        float: none;
    }

    .widget-title,.widgettitle { /* This sets the size and style of the sidebar titles */
    font-size 		: 	<?php echo $sidebar_title_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($sidebar_title_style) ?>;
    color 			: 	#<?php echo $sidebar_title_color; ?>;
    text-decoration :   <?php echo $sidebar_title_decoration ?>;
<?php if ($sidebar_title_weight): ?>
    font-weight     :   <?php echo $sidebar_title_weight ?>;
<?php endif ?>
<?php if ($sidebar_title_italic): ?>
    font-style      :   <?php echo $sidebar_title_italic ?>;
<?php endif ?>
<?php if ($sidebar_title_case != 'none'): ?>
    text-transform  :   <?php echo $sidebar_title_case ?>;
<?php endif ?>
    margin-bottom 	: 	10px;
    padding-bottom 	: 	0;
    }

    .widget-container { /* This sets a small margin below each widget */
    margin			: 	0 0 1.5em 0;
    }
    .widget-container img {
    max-width: 100%;
    height: auto;
    }

    #searchform label { /* This hides the search form label */
    display 		: 	none;
    }


    /*---------styling for custom menus in sidebar-------------*/

    .widget_nav_menu ul.menu {
    line-height		:	.5;
    }

    .widget_nav_menu ul.menu li a:link, .widget_nav_menu ul.menu li a:visited, .widget_nav_menu ul.menu li .current_page_item a:visited, .widget_nav_menu ul.menu li a:hover  {
    background		: 	transparent;
    padding-left	: 	0px;
    font-family     :   <?php echo $fonts->get_css_value($sidebar_font_style) ?>;
    font-size		:	<?php echo $sidebar_font_size; ?>px;
    line-height		:	1.5;
    padding			:	0px 0px;
    }

    .widget_nav_menu ul.menu li {
    border-bottom	: 	0px;
    }

    .widget_nav_menu ul.menu ul.sub-menu { /*-----hides sidebar custom menu submenus-----*/
    display			:	none;
    }

    /*--------search form styles--------*/
    #searchform {
    position  :  relative;
    overflow  : hidden;
    width   :  90%;
    height   :  24px;
    padding-bottom :  5px;
    padding-left :  3px;
    background  :  #fdfdfd;
    border   :  1px solid #ccc;
    /*--shadow--*/
    -moz-box-shadow: inset 0 0 3px #888;
    -webkit-box-shadow:  inset 0 0 5px #888;
    box-shadow:  inset 0 0 5px #888;
    }

    #searchform input#s{
    width   :  88%;
    height   :  24px;
    padding-top  :  3px;
    padding-bottom :  4px;
    background  :  transparent;
    border   :  0px;
    color   :  #a1a1a1;
    font-size  :  16px;
    }

    div.entry-content #searchform input#s {
    width   :  93%;
    }

    #footer-widgets #searchform {
    margin-top  :  25px;
    }

    #footer-widgets #searchform input#s {
    width   :  85%;
    }

    /*---search button----*/
    #searchsubmit {
    position  : absolute;
    width   :  24px;
    height   :  24px;
    text-indent  :  -1000em;
    background  :  transparent url('../images/search_circle.png') no-repeat scroll 0 0;
    border   : 0 none;
    top   : 3px;
    right   : 3px;
    }

    #searchsubmit:hover {
    -ms-filter  :  "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
    filter   :  alpha(opacity=50);
    opacity   :  .5;
    cursor   : pointer;
    }

    /* The following style the lists in the widgets */

    .widget-area ul {
    list-style		: 	none;
    margin-left		: 	0;
    }

    .widget-area ul ul {
    list-style		: 	disc;
    margin-left		: 	0;
    }

    .widget-area ul ul li { /* This styles the sidebar bullet list. */
    list-style		: 	none;
    line-height		: 	2;
    padding-left	: 	0px;
    border-bottom	: 	1px dotted #ccc;
    }
    
    .widget-area ul ul li a {
    line-height		: 	1.5;
    }

    .widget-area ul ul ul {
    margin-left		: 	0px;
    }


    /* Gallery Styles
    -------------------------------------------------------------- */

    .galleria-info-text {
    }

    .galleria-info-title {
    /*color 			: 	#<?php echo $font_color; ?>;*/
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    }

    .galleria-info-description {
    /*color 			: 	#<?php echo $font_color; ?>;*/
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    }

    .photocrati_nojava {
    width			:	100%;
    text-align		:	center;
    margin			:	0 auto;
    }

    .photocrati_nojava img {
    max-width		:	100% !important;
    margin			:	5px auto;
    }

    .iframe_wrapper {
    width			:	100%;
    text-align		:	center;
    }

    .gallery {
    margin-bottom	:	15px;
    }

    .gallery img {
    border			:	0px;
    }


    /* Album Styles
    -------------------------------------------------------------- */

    .album_wrapper {
    width			:	100%;
    clear			:	both;
    margin-bottom	:	15px;
    }
    
    .album_list:after {
			content: " ";
			display: table;
			clear: both;
    }

    .album_list .image_wrapper {
    width			:	25%;
    }

    .album_list .image_wrapper img {
    max-width		:	90% !important;
    max-height		:	<?php echo (150 - ($albuml_line_size * 2)); ?>px;
    }

    .album_list .meta_wrapper {
    width			:	75%;
    margin-top      :   0px;
    }

    .album_list h4 {
    margin-top      :   0px;
    }


    /* E-Commerce Gallery Styles
    -------------------------------------------------------------- */

    .ecommerce_wrapper {
    width			:	100%;
    height			:	auto;
    position		:	relative;
    margin-bottom	:	10px;
    clear			:	both;
    }

    .ecommerce {
    float			:	left;
    text-align		:	center;
    }

    .ecommerce .meta_wrapper .quantity {
    width			:	40%;
    float			:	left;
    }

    .ecommerce .meta_wrapper .quantity input {
    padding			:	3px;
    border			:	1px solid #999;
    font-size		:	11px;
    }

    .addto {
    width			:	100%;
    float			:	right;
    text-align		:	right;
    }

    .addto a, a.iframe {
    text-decoration	:	none;
    }

    .addto button, button.addto, button#addto, button#addto2, button#addto3 {
    display			:	block;
    width			:	auto;
    overflow		:	visible;
    float			:	right;
    margin			:	2px 0 0 0;
    background		:   #<?php echo $ecomm_but_color; ?> url(../images/button-overlay.png) repeat-x;
    border			:	1px solid #<?php echo $ecomm_butborder_color; ?>;
    font-family		:	"Lucida Grande", Tahoma, Arial, Verdana, sans-serif;
    font-size		:	11px;
    line-height		:	130%;
    text-decoration	:	none;
    font-weight		:	bold;
    color			:	#<?php echo $ecomm_buttext_color; ?>;
    cursor			:	pointer;
    padding			:	3px 5px; /* Links */
    -moz-border-radius	: 	8px;
    border-radius	: 	8px;
    }

    button#addto2 {
    padding			:	5px 5px 5px 22px; /* Links */
    }

    .addto button img, button#addto2 img {
    border			:	0;
    clear			:	none;
    position		:	absolute;
    margin-left		:	-17px;
    }

    .addto img {
    margin			:	0 3px -1px 0 !important;
    padding			:	0;
    border			:	none;
    cursor			:	pointer;
    }


    /* E-Commerce Add to Cart Window
    -------------------------------------------------------------- */
    .ecommerce_lightbox #fancybox-overlay{
        overflow: hidden;
    }
    .ecommerce_lightbox #fancybox-content {
    -webkit-overflow-scrolling: touch !important;
    overflow: scroll !important;
    }

    #cart_wrapper {
    width			:	98%;
    }

    .cart_header {
    width			:	100%;
    padding			:	3px 6px;
    background		:	#<?php echo $ecomm_back_color; ?>;
    color			:	#<?php echo $ecomm_font_color; ?>;
    font-size		:	13px;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    border-left		:	0;
    border-right	:	0;
    }

    .cart_image {
    width			:	30%;
    float			:	left;
    margin-top      :   10px;
    }

    #shopping_cart_wrapper .cart_image {
    margin-top      :   0px;
    }


    .checkout_fields_table {
    width           :   82%;
    float           :   left;
    }


    .checkout_fields_table th {
    text-align      :   right;
    padding-right   :   5px;
    }

    .checkout_fields_table td {
    text-align: left;
    }

    .checkout_fields_table .textfield {
    width           :   100%;
    }

    .cart_image img {
    max-width		:	<?php echo (175-($ecomm_line_size*2)); ?>px;
    border			:	<?php echo $ecomm_line_size; ?>px solid #<?php echo $ecomm_line_color; ?>;
    }

    .cart_data {
    width			:	70%;
    float			:	left;
    font-size		:	13px;
    }

    .cart_qty, .cart_desc, .cart_amt, .cart_line {
    float			:	left;
    margin			:	2px 0;
    height			:	30px;
    font-size		:	12px;
    }

    .cart_qty {
    width			:	15%;
    }

    .cart_qty input {
    width			:	35px;
    padding			:	2px;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    font-size		:	12px;
    }

    .cart_desc {
    width			:	49%;
    padding-top		:	5px;
    }

    .cart_amt {
    width			:	18%;
    padding-top		:	5px;
    }

    .cart_line {
    width			:	18%;
    padding-top		:	2px;
    }

    .cart_line input {
    width			:	55px;
    border			:	0;
    padding			:	0;
    font-size		:	12px;
    }

    .cart_clear {
    border-bottom	:	1px solid #<?php echo $ecomm_line_color; ?>;
    margin-bottom	:	6px;
    }

    .cart_total {
    width			:	82%;
    font-weight		:	bold;
    float			:	left;
    padding-top		:	3px;
    font-size		:	12px;
    }

    .cart_total_amount {
    width			:	18%;
    float			:	left;
    font-size		:	12px;
    }

    .cart_total_amount input {
    width			:	55px;
    border			:	0;
    padding			:	0;
    font-size		:	12px;
    }

    .titles {
    height			:	22px;
    padding-top		:	5px;
    color			:	#<?php echo $ecomm_font_color; ?>;
    background		:	#<?php echo $ecomm_back_color; ?>;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    border-left		:	0;
    border-right	:	0;
    }

    .buttons_clear {
    height			:	20px;
    }

    .widget_wrapper {
    width			:	100%;
    height			:	28px;
    clear			:	both;
    position		:	relative;
    top				:	-5px;
    }

    #cart_widget {
    float			:	right;
    font-size		:	12px;
    }

    #cart_widget p {
    margin			:	2px 5px 0 0;
    }


    /* E-Commerce Shopping Cart Page
    -------------------------------------------------------------- */

    #shopping_cart_wrapper {
    width			:	100%;
    margin			:	5px auto;
    }

    #shopping_cart_wrapper .buttons {
    width			:	100%;
    text-align		:	right;
    margin			:	0 auto;
    padding-bottom	:	25px;
    }

    #shopping_cart_wrapper .cart_contents {
    width			:	100%;
    clear			:	both;
    margin			:	10px 0;
    }

    #shopping_cart_wrapper .item_wrapper {
    width			:	100%;
    clear			:	both;
    margin			:	5px 0;
    padding			:	5px 0 10px 0;
    border-bottom	:	1px dashed #<?php echo $ecomm_line_color; ?>;
    height			:	auto;
    overflow		: 	auto;
    }

    #shopping_cart_wrapper .cart_contents .cart_image {
    width			:	25%;
    float			:	left;
    }

    #shopping_cart_wrapper .cart_contents .cart_image img {
    max-height		:	<?php echo (150-($ecomm_line_size*2)); ?>px;
    border			:	<?php echo $ecomm_line_size; ?>px solid #<?php echo $ecomm_line_color; ?>;
    }

    #shopping_cart_wrapper .cart_contents .cart_items {
    width			:	75%;
    float			:	left;
    }

    #shopping_cart_wrapper .cart_contents .cart_qty,
    #shopping_cart_wrapper .cart_contents .cart_desc,
    #shopping_cart_wrapper .cart_contents .cart_amt,
    #shopping_cart_wrapper .cart_contents .cart_line {
    height			:	25px;
    font-size		:	13px;
    }

    #shopping_cart_wrapper .cart_contents .cart_qty {
    width			:	8%;
    padding-top		:	0;
    }

    #shopping_cart_wrapper .cart_contents .cart_desc {
    width			:	70%;
    padding-top		:	0;
    }

    #shopping_cart_wrapper .cart_contents .cart_amt {
    width			:	11%;
    padding-top		:	0;
    }

    #shopping_cart_wrapper .cart_contents .cart_line {
    width			:	11%;
    padding-top		:	0;
    font-weight		:	bold;
    text-align		:	right;
    }

    #shopping_cart_wrapper .cart_contents .titles {
    height			:	20px;
    padding-top		:	2px;
    }

    #shopping_cart_wrapper .cart_total_wrapper {
    width			:	260px;
    padding			:	10px;
    float			:	right;
    clear			:	both;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    background		:	#<?php echo $ecomm_back_color; ?>;
    color			:	#<?php echo $ecomm_font_color; ?>;
    }

    #shopping_cart_wrapper .cart_total_wrapper .cart_total {
    width			:	58%;
    font-weight		:	bold;
    float			:	left;
    padding-top		:	3px;
    font-size		:	13px;
    text-align		:	right;
    }

    #shopping_cart_wrapper .cart_total_wrapper .cart_total_amount {
    width			:	42%;
    float			:	left;
    font-size		:	13px;
    font-weight		:	bold;
    text-align		:	right;
    }

    #shopping_cart_wrapper .cart_total_wrapper .cart_total_amount input {
    width			:	60px;
    border			:	0;
    padding			:	0;
    font-size		:	13px;
    text-align		:	right;
    font-weight		:	bold;
    color			:	#<?php echo $ecomm_font_color; ?>;
    background		:	#<?php echo $ecomm_back_color; ?>;
    }

    .checkout_fields {
    display			:	none;
    width			:	100%;
    clear			:	both;
    padding			:	10px 0;
    text-align		:	center;
    }

    .checkout_fields .checkout_wrapper {
    width			:	65%;
    min-height		:	300px;
    clear			:	both;
    margin			:	0 auto;
    padding			:	15px;
    text-align		:	left;
    }

    .checkout_fields .checkout_wrapper .lable {
    width			:	30%;
    float			:	left;
    font-weight		:	bold;
    margin-bottom	:	10px;
    }

    .checkout_fields .checkout_wrapper .field {
    width			:	70%;
    float			:	left;
    text-align		:	right;
    margin-bottom	:	10px;
    }

    .checkout_fields .checkout_wrapper .field input {
    width			:	350px;
    }

    .checkout_fields .checkout_wrapper .field input,
    .checkout_fields .checkout_wrapper .field select {
    padding			:	3px;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    font-size		:	13px;
    }

    .checkout_footer {
    width			:	100%;
    clear			:	both;
    padding			:	0 0 15px 0;
    font-size		:	12px;
    text-align		:	justify;
    }

    .checkout_image {
    width			:	100%;
    clear			:	both;
    padding			:	10px 0 0 0;
    text-align		:	right;
    }


    /* Footer Wrapper
    -------------------------------------------------------------- */

    .footer_container { /* This sets the size and font styles of the footer area */
    clear: both;
    width: auto;
    margin:	0 auto;
<?php if ($left_header): ?>
<?php if($layout_alignment == 'left'): ?>
    margin: 0;
<?php else: ?>
    margin: 0 auto;
<?php endif ?>
    margin-left: <?php echo ((int)$header_width) + intval($header_margin_left) + intval($header_margin_right); ?>px;
<?php endif ?>
    }

    .footer_wrapper { /* This sets the size and font styles of the footer area */
    clear: both;
    width: auto;
    margin:	0 auto;
<?php if ($left_header): ?>
<?php echo Photocrati_Style_Manager::build_width_property_set($layout_width, $layout_width_unit, $layout_width_min, $layout_width_min_unit, $layout_width_max, $layout_width_max_unit); ?>
<?php if($layout_alignment == 'left'): ?>
    margin: 0;
<?php else: ?>
    margin: 0 auto;
<?php endif ?>
<?php else: ?>
    width: auto;
<?php endif ?>
    padding: 5px 0;
    text-align 		: 	center;
    background		:	<?php 
    if($footer_background <> 'transparent') {
    	if ($footer_opacity >= 100) {
  			echo '#' . $footer_background; 
    	} 
    	else {
    		echo 'rgba(' . implode(',', Photocrati_Style_Manager::color_hex2rgb($footer_background)) . ',' . round($footer_opacity / 100, 2) . ')'; 
    	}
    } 
    else { 
    	echo $footer_background; 
    }
    ?>;
    min-height			:	<?php echo $footer_height; ?>px;
    clear			:	both;
    z-index			:	2;
<?php if($footer_drop_shadow_size > 0): ?>
    -moz-box-shadow: 0px <?php echo -intval(($footer_drop_shadow_size)); ?>px <?php echo $footer_drop_shadow_size; ?>px <?php echo -intval(($footer_drop_shadow_size)); ?>px rgb(0, 0, 0);
    -webkit-box-shadow: 0px <?php echo -intval(($footer_drop_shadow_size)); ?>px <?php echo $footer_drop_shadow_size; ?>px <?php echo -intval(($footer_drop_shadow_size)); ?>px rgb(0, 0, 0);
		box-shadow: 0px <?php echo -intval(($footer_drop_shadow_size)); ?>px <?php echo $footer_drop_shadow_size; ?>px <?php echo -intval(($footer_drop_shadow_size)); ?>px rgb(0, 0, 0);
<?php endif ?>
    }
		
    /* Footer Widget Styles
    -------------------------------------------------------------- */

    .footer-widget-area { /* This is the footer widget wrapper */
    background:	none;
<?php if ($left_header || $one_column): ?>
    width: auto;
    padding: 5px 10px 5px 10px;
<?php else: ?>
<?php echo Photocrati_Style_Manager::build_width_property_set($layout_width, $layout_width_unit, $layout_width_min, $layout_width_min_unit, $layout_width_max, $layout_width_max_unit); ?>
<?php endif ?>
<?php if($left_header && $layout_alignment == 'left'): ?>
    margin: 0;
<?php else: ?>
    margin: 0 auto;
<?php endif ?>
    min-height		:	50px;
    color			:	#<?php echo $footer_font_color; ?>;
    font-size		:	<?php echo $footer_font; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($footer_font_style) ?>;
<?php if ($footer_font_weight): ?>
    font-weight     :   <?php echo $footer_font_weight ?>;
<?php endif ?>
<?php if ($footer_font_italic): ?>
    font-style      :   <?php echo $footer_font_italic ?>;
<?php endif ?>
    text-decoration :   <?php echo $footer_font_decoration ?>;
<?php if ($footer_font_case != 'none'): ?>
    text-transform  :   <?php echo $footer_font_case ?>;
<?php endif ?>
    }

    .footer-widget-container { /* This is the footer widget container */
    display			:	inline-block;
    background		:	none;
    height			:	auto;
    float			:	left;
    padding			:	10px;
    text-align		:	left;
    margin-bottom	:	5px;
    }

    .footer-widget-container .widget-title { /* This sets the style of the footer widget titles */
    font-size		:	<?php echo $footer_widget_title; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($footer_widget_style) ?>;
    color			:	#<?php echo $footer_widget_color; ?>;
<?php if ($footer_widget_weight): ?>
    font-weight     :   <?php echo $footer_widget_weight ?>;
<?php endif ?>
<?php if ($footer_widget_italic): ?>
    font-style      :   <?php echo $footer_widget_italic ?>;
<?php endif ?>
<?php if ($footer_widget_case != 'none'): ?>
    text-transform  :   <?php echo $footer_widget_case ?>;
<?php endif ?>
    text-decoration :   <?php echo $footer_widget_decoration ?>;
    }

    .footer-widget-container a { /* This sets the color of the footer widget links */
    color			:	#<?php echo $footer_link_color; ?>;
    }

    .footer-widget-container a:hover,
    .footer-widget-container a:active { /* This sets the color and style of the hover and active states of the footer widget links */
    color			:	#<?php echo $footer_link_hover_color; ?>;
    text-decoration	:	<?php echo $footer_link_hover_style; ?>;
    }

    #footer-widgets .footer-widget-container ul {
    margin-left: 0px;
    }

    #footer-widgets .footer-widget-container ul li { /* This styles the footer widget bullet styles */
    list-style-type	: 	none;
    line-height		: 	2;
    padding-left	: 	0px;
    border-bottom	: 	1px dotted #999;
    }

    #footer-widgets .footer-widget-container ul li a:visited { /* This styles the footer widget bullet styles */
    color			: 	#<?php echo $footer_font_color; ?>;
    }


    /* Footer Style
    -------------------------------------------------------------- */

    #footer { /* This sets the size and font styles of the footer area */
    clear			: 	both;
    width			: 	auto;
    text-align 		: 	center;
    margin			:	15px auto 15px auto;
    padding-top 	: 	5px;
    color 			: 	#<?php echo $footer_font_color; ?>;
    font-size		: 	<?php echo $footer_font; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($footer_font_style) ?>;
    }

    #footer a { /* This sets the color of the footer links */
    color			:	#<?php echo $footer_link_color; ?>;
    }

    #footer a:hover,
    #footer a:active { /* This sets the color and style of the hover and active states of the footer links */
    color			:	#<?php echo $footer_link_hover_color; ?>;
    text-decoration	:	<?php echo $footer_link_hover_style; ?>;
    }

    #footer #site-info {
    clear			: 	both;
    margin			:	5px 7px 0 7px;
    font-size		:	14px;
    }

    #footer #site-info p {
    z-index			:	3;
    }
    
    /* background slideshow styles */ 
    #supersized {
    	margin-left:0;
    }
		#supersized li {
			padding-left:0;
		}
		
		
    /* responsive CSS Code
    -------------------------------------------------------------- */
		@media screen and (min-width: 0px) and (max-width: 1024px) {
		  #content-sm {
				float: none;
				clear: both;
		  	width: 100%;
		  }
		  
			#sidebar {
				float: none;
				clear: both;
		  	width: 100%;
			}
		}

    /* Custom CSS Code
    -------------------------------------------------------------- */
<?php
echo str_replace("\'", "'", str_replace('\"', '"', $custom_css_modern));
?>
		
    /* desktop only CSS adjustments that override custom CSS
    -------------------------------------------------------------- */
		@media screen and (min-width: 1025px) {
<?php
echo str_replace("\'", "'", str_replace('\"', '"', $custom_css_modern_desktop));
?>
		}

		
    /* responsive CSS adjustments that override custom CSS
    -------------------------------------------------------------- */
		@media screen and (min-width: 0px) and (max-width: 1024px) {
		
    #main_container {
    	width: auto;
    	min-width: none;
    	max-width: none;
    }
    #wrapper {
    	width: auto;
    	min-width: none;
    	max-width: none;
			margin-left: 0;
			margin-right: 0;
    }
		#main {
    	width: auto;
    	min-width: none;
    	max-width: none;
			margin-top: 0;
			margin-left: 0;
			margin-right: 0;
		}

		/* cancel fixed positioning on small screens */
		#header {
			position: static;
			max-height: none;
			width: auto;
			height: auto;
		}
		
		#header:before,
		#header:after {
			content: " ";
			display: table;
		}
		#header:after {
			clear: both;
		}
    #masthead {
    	width: auto;
    	min-width: none;
    	max-width: none;
		  text-align: center;
    }

    #branding {
		  width: auto;
    	float: none;
		  clear: both;
		  text-align: center;
		  margin: 0;
		  padding-top: 15px;
		  padding-bottom: 25px;
    }
    #branding h1 {
		  text-align: center;
    }
    #branding #blog-title {
			margin-left: 0;
			margin-right: 0;
		  text-align: center;
    }
    #branding #blog-title h1 {
			margin-left: 0;
			margin-right: 0;
		  text-align: center;
    }
    #branding #blog-title .description {
			margin-left: 0;
			margin-right: 0;
		  text-align: center;
    }
    
	  #content-sm {
	  	width: auto;
	  	margin-left: 10px;
	  	margin-right: 10px;
	  }
	  
		#sidebar {
			border: none;
		}
    .footer_container {
    	width: auto;
    	min-width: none;
    	max-width: none;
			margin-left: 0;
    }
    .footer_wrapper {
    	width: auto;
    	min-width: none;
    	max-width: none;
			margin-left: 0;
    }
    .footer-widget-area { 
    	width: auto;
    	min-width: none;
    	max-width: none;
    	margin-left: 10px;
    	margin-right: 10px;
    }
		.footer-widget-container {
			display: block;
			float: none;
			clear: both;
	  	width: auto;
	  	margin: 0 auto 10px auto;
		}			
			
<?php
/* Make adjustments for responsive menus if skin is not legacy 
	 NOTE: this was part of past code before the style_skin stuff so it's now probably obsolete but leaving for safety -- basically whenever $style_skin is not 'legacy' then $menu_skin will never be 'legacy' (look above)
*/
if ($menu_skin != 'legacy'): ?>
    
		/* adjustments for responsive menus */
    #menu_wrapper {
		  width: auto;
    	float: none;
		  clear: both;
		  margin: 0 auto 10px auto;
		  display: inline-block;
		  text-align: center;
    }
		
		.photocrati-menu > ul > li {
			display: block;
			clear: both;
		}
		
		.photocrati-menu > ul > li > a,
		.photocrati-menu > ul > li > a:link,
		.photocrati-menu > ul > li > a:visited,
		.photocrati-menu > ul > li > a:hover,
		.photocrati-menu > ul > li > a:active {
			padding-top: 5px;
			padding-bottom: 5px;
		}
		
		.photocrati-menu .menu-item-has-children ul {
			display: none;
			position: static;
			top: auto;
			left: auto;
			text-align: center;
		}
		
		.photocrati-menu .menu-item-has-children .menu-item-has-children ul {
			display: none;
			position: static;
			left: auto;
			top: auto;
		}
		
		.photocrati-menu .menu-item-has-children .menu-item-has-children ul li a {
			padding-left: 28px;
		}
<?php endif ?>

    /* Custom CSS Code for mobile
    -------------------------------------------------------------- */
<?php
echo str_replace("\'", "'", str_replace('\"', '"', $custom_css_modern_mobile));

?>
		}
    
		/* for high pixel density displays */
		@media
		only screen and (-webkit-min-device-pixel-ratio: 1.3),
		only screen and (   min--moz-device-pixel-ratio: 1.3),
		only screen and (   -moz-min-device-pixel-ratio: 1.3),
		only screen and (     -o-min-device-pixel-ratio: 13/10),
		only screen and (        min-device-pixel-ratio: 1.3),
		only screen and (                min-resolution: 120dpi),
		only screen and (                min-resolution: 1.3dppx) { 
		
<?php echo Photocrati_Style_Manager::build_font_list_stylesheet(); ?>
		}

		/* for high pixel density displays */
		@media
		only screen and (-webkit-min-device-pixel-ratio: 2),
		only screen and (   min--moz-device-pixel-ratio: 2),
		only screen and (   -moz-min-device-pixel-ratio: 2),
		only screen and (     -o-min-device-pixel-ratio: 2/1),
		only screen and (        min-device-pixel-ratio: 2),
		only screen and (                min-resolution: 192dpi),
		only screen and (                min-resolution: 2dppx) { 
		
<?php echo Photocrati_Style_Manager::build_font_list_stylesheet(); ?>
		}
