<?php
define('THIS_IS_SOMEWHAT',__('This is somewhat embarrassing, isn&rsquo;t it?','photomaker'));
define('IT_SEEMS_WE',__('It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.', 'photomaker'));
define('MOST_USED_CATEGORIES',__('Most Used Categories', 'photomaker'));
define('MONTHLY_ARCHIVES',__('Try looking in the monthly archives. %1$s', 'photomaker'));
define('SORRY_NO_POST_MATCHED',__('Sorry, no posts matched your criteria.', 'photomaker'));
define('NOTHING_FOUND',__('Nothing Found here', 'photomaker'));
define('NOTHING_MATCHED',__('Sorry, but nothing matched your search criteria.', 'photomaker'));
define('CATEGORIES',__('Categories', 'photomaker'));
define('ARCHIVES',__('Archives', 'photomaker'));
define('BLOG_ARCHIVES',__('Blog Archives', 'photomaker'));
define('CATEGORY_ARCHIVES',__('Category Archives: %s', 'photomaker'));
define('PAGE',__('Page %s', 'photomaker'));
define('SEARCH_RESULT',__('Search Results for: %s', 'photomaker'));
define('TAG_ARCHIVES',__('Tag Archives: %s', 'photomaker'));
define('DAILY_ARCHIVES',__('Daily Archives: %s', 'photomaker'));
define('LCN_MAP',__('Location Map','photomaker'));
define('YEARLY_ARCHIVES',__('Yearly Archives: %s', 'photomaker'));
define('AUTHOR_ARCHIVES',__('Author Archives: %s', 'photomaker'));
define('ABOUT',__('About: %s', 'photomaker'));
define('HOME_TEXT',__('Home', 'photomaker'));
define('THIS_ENTRY_WAS_POSTED_IN',__('This entry was posted in %1$s','photomaker'));
define('PERMALINK',__('permalink','photomaker'));
define('BOOKMARK_THE',__('Bookmark the','photomaker'));
define('PRIMARY_WIDGET',__('Primary Widget Area', 'photomaker'));
define('THE_PRIMARY_WIDGET',__('The primary widget area', 'photomaker'));
define('SECONDRY_WIDGET',__('Secondary Widget Area', 'photomaker'));
define('THE_SECONDRY_WIDGET',__('The secondary widget area', 'photomaker'));
define('SMT_CMT',__('Submit Comment', 'photomaker'));
define('LV_CMT',__('Leave a Comment', 'photomaker'));
define('OLDER_POSTS',__('&larr; Older posts', 'photomaker'));
define('NEWER_POSTS',__('Newer posts &rarr;', 'photomaker'));
define('PREV_POST',__(' Previous Post', 'photomaker'));
define('NEXT_POST',__('Next Post ', 'photomaker'));
define('READ_MORE',__('Read More', 'photomaker'));
define('SND_MSG',__('Send Your Message', 'photomaker'));
define('RETURN_TO',__('Return to %s', 'photomaker'));
define('BY_AUTHOR',__('By %2$s', 'photomaker'));
define('VIEW_ALL_POST_BY',__('View all posts by %s', 'photomaker'));
define('PUBLISHED_BY',__('Published %2$s', 'photomaker'));
define('FULL_SIZE_IS_PIXEL',__('Full size is %s pixels', 'photomaker'));
define('LINK_TO_FULL_SIZE_IMAGE',__('Link to full-size image', 'photomaker'));
define('EDIT_TEXT',__('Edit', 'photomaker'));
define('CONTINUE_READING',__('Continue reading &rarr;', 'photomaker'));
define('PAGES_COLON',__('Pages:', 'photomaker'));
define('CONTINUE_READING_DOTS',__('Read More', 'photomaker'));
define('POSTED_BY',__('Posted by', 'photomaker'));
define('AND_TAGGED',__('and tagged','photomaker'));
define('SMT_MSG',__('Submit Message','photomaker'));
define('CONTACT_NAME',__('Your Name','photomaker'));
define('CONTACT_EMAIL',__('Your Email','photomaker'));
define('CONTACT_MESSAGE',__('Your Message','photomaker'));
define('FORM_SEARCH',__('Search','photomaker'));
define('CMNT_CLSD',__('Comments are closed.','photomaker'));
define('NO_CMNT',__('No Comments','photomaker'));
define('ONE_CMNT',__('One Comments','photomaker'));
define('CMNT',__('Comments','photomaker'));
?>